// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8eQZy5xry36pEn1xTFSb3G
// Component: 2n2-TSJJMMH_
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css" // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: 8eQZy5xry36pEn1xTFSb3G/projectcss
import * as sty from "./PlasmicRatings.module.css" // plasmic-import: 2n2-TSJJMMH_/css
import StarIcon from "./icons/PlasmicIcon__Star" // plasmic-import: AL_Sm-K9zQ1g/icon

export const PlasmicRatings__VariantProps = new Array("stars")

export const PlasmicRatings__ArgProps = new Array("numReviews")

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant(variants, "stars", "five"),
          [sty.rootstars_four]: hasVariant(variants, "stars", "four"),
          [sty.rootstars_one]: hasVariant(variants, "stars", "one"),
          [sty.rootstars_three]: hasVariant(variants, "stars", "three"),
          [sty.rootstars_two]: hasVariant(variants, "stars", "two"),
          [sty.rootstars_zero]: hasVariant(variants, "stars", "zero"),
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___6ChC, {
              [sty.svgstars_five___6ChCsVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_zero___6ChC2GP0A]: hasVariant(
                variants,
                "stars",
                "zero"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__b7MH7, {
              [sty.svgstars_five__b7MH7SVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__b7MH7GUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__b7MH7LBryb]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__b7MH7A77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__b7MH7QJ17X]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__b7MH72GP0A]: hasVariant(
                variants,
                "stars",
                "zero"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__reMrs, {
              [sty.svgstars_five__reMrssVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__reMrsGUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__reMrsLBryb]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__reMrsa77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__reMrsqJ17X]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__reMrs2GP0A]: hasVariant(
                variants,
                "stars",
                "zero"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__if4G3, {
              [sty.svgstars_five__if4G3SVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__if4G3GUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__if4G3LBryb]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__if4G3A77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__if4G3QJ17X]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__if4G32GP0A]: hasVariant(
                variants,
                "stars",
                "zero"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__awxUg, {
              [sty.svgstars_five__awxUGsVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__awxUggUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__awxUglBryb]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__awxUGa77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__awxUGqJ17X]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__awxUg2GP0A]: hasVariant(
                variants,
                "stars",
                "zero"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__marNb, {
              [sty.svgstars_five__marNbsVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__marNbGUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__marNbLBryb]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__marNba77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__marNbqJ17X]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__marNb2GP0A]: hasVariant(
                variants,
                "stars",
                "zero"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__fekHi, {
              [sty.svgstars_five__fekHisVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__fekHiGUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__fekHia77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__fekHiqJ17X]: hasVariant(
                variants,
                "stars",
                "two"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__k16H, {
              [sty.svgstars_five__k16HsVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__k16HGUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__k16Ha77Ag]: hasVariant(
                variants,
                "stars",
                "three"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__cxnGn, {
              [sty.svgstars_five__cxnGNsVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__cxnGngUwP]: hasVariant(
                variants,
                "stars",
                "four"
              ),
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__xts8E, {
              [sty.svgstars_five__xts8EsVuHr]: hasVariant(
                variants,
                "stars",
                "five"
              ),
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews),
      })}
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps,
    })

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings"
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`
  }
  return func
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps,
  }
)

export default PlasmicRatings
/* prettier-ignore-end */
