// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8eQZy5xry36pEn1xTFSb3G
// Component: BTpi3t6AHSs
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: 9kaYRQveml8/component
import ProductCarousel from "../../ProductCarousel" // plasmic-import: T3CyYLQoVwtk/component
import ProductCard from "../../ProductCard" // plasmic-import: _beqs1GTsSZ3/component
import Ratings from "../../Ratings" // plasmic-import: 2n2-TSJJMMH_/component
import FeatureItem from "../../FeatureItem" // plasmic-import: wuHoIoxQ5K_/component
import BlogPost from "../../BlogPost" // plasmic-import: 5FoW80CVPvVE/component
import Footer from "../../Footer" // plasmic-import: Gq5NoMrsOpL/component
import { useScreenVariants as useScreenVariantsn35PTdUkddpF } from "./PlasmicGlobalVariant__Screen" // plasmic-import: N35pTdUkddpF/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css" // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: 8eQZy5xry36pEn1xTFSb3G/projectcss
import * as sty from "./PlasmicHome.module.css" // plasmic-import: BTpi3t6AHSs/css
import arrivals1ARodXqn4MGNu from "./images/arrivals1.png" // plasmic-import: ARodXqn4mGNu/picture
import arrivals26Bm8BrYhBfvl from "./images/arrivals2.png" // plasmic-import: 6bm8BrYHBfvl/picture
import arrivals3PmhTar44KwVl from "./images/arrivals3.png" // plasmic-import: PmhTar44KwVl/picture
import arrivals4KvLOpmN12Cc from "./images/arrivals4.png" // plasmic-import: kvL_opmN12cc/picture
import arrivals5FRvspW87Ebgm from "./images/arrivals5.png" // plasmic-import: FRvspW87ebgm/picture
import arrivals6FnvyhQftNL4 from "./images/arrivals6.png" // plasmic-import: fnvyhQftN_l4/picture
import arrivals78PXolbtgZezo from "./images/arrivals7.png" // plasmic-import: 8pXolbtgZezo/picture
import arrivals8Mo34AkbOVni from "./images/arrivals8.png" // plasmic-import: mo3-4akbOVni/picture
import f2YZYckXJeE from "./images/f2.jpeg" // plasmic-import: yZ_yckX-JeE_/picture
import f3MiMyYimZ0 from "./images/f3.jpeg" // plasmic-import: MI-MyYim__Z0/picture
import f4AF6LDx447Yl from "./images/f4.jpeg" // plasmic-import: aF6lDX_447Yl/picture
import b1GShyHTjVshz from "./images/b1.jpeg" // plasmic-import: GShy-HTjVSHZ/picture
import b2PHhMNfXbuCz from "./images/b2.jpeg" // plasmic-import: pHhMNfXBUCz_/picture
import b36GzoZlVFr8XJ from "./images/b3.jpeg" // plasmic-import: 6gzoZlVFr8xJ/picture
import adidas8A8TrpRztth from "./images/adidas.png" // plasmic-import: 8a8_TrpRZTTH/picture
import hmF0QHspbUgvy from "./images/hm.png" // plasmic-import: f_0QHspbUGVY/picture
import kappaYvzubA4M7Mg from "./images/kappa.png" // plasmic-import: YVZUB-A4M7MG/picture
import lacosteB6EjqEha8XcA from "./images/lacoste.png" // plasmic-import: B6ejqEha8xcA/picture
import levisTToXfiy87MX from "./images/levis.png" // plasmic-import: TToXFIY87M-x/picture

export const PlasmicHome__VariantProps = new Array()

export const PlasmicHome__ArgProps = new Array()

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsn35PTdUkddpF(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xCEl)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__lmPs6)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__zgUze)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__iaMcN)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___916L0
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___6SbMv)}
            >
              <div className={classNames(projectcss.all, sty.column___0BXI)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mc05S
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ihPMz)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals1ARodXqn4MGNu,
                        fullWidth: 120,
                        fullHeight: 120,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__kNlv3
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__paSBj)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__bNuv
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__sl64)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals26Bm8BrYhBfvl,
                        fullWidth: 138,
                        fullHeight: 116,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__qa5S4
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Single Armchair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__l625)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iYUgg
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__vp0LN)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals3PmhTar44KwVl,
                        fullWidth: 135,
                        fullHeight: 116,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__cUjIr
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Armchair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___1Ih8M)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__u0GN
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___6IkP)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals4KvLOpmN12Cc,
                        fullWidth: 100,
                        fullHeight: 130,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__lq6HT
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Stylish Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__udluy)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__afxyg
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__s12MP)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals5FRvspW87Ebgm,
                        fullWidth: 105,
                        fullHeight: 127,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$120.00"}
                  title={"Modern Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__bJZfk)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qgAi9
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__vdcrB)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals6FnvyhQftNL4,
                        fullWidth: 176,
                        fullHeight: 123,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={true}
                  price={"$140.00"}
                  title={"Mapple Wood Dinning Table"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__qLxbI)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nx2Ym
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pb5BJ)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals78PXolbtgZezo,
                        fullWidth: 160,
                        fullHeight: 120,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={true}
                  price={"$90.00"}
                  title={"Arm Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__j9Ib)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aeih
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___4IEFc)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals8Mo34AkbOVni,
                        fullWidth: 191,
                        fullHeight: 101,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$140.00"}
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0QzCm
                      )}
                    >
                      {"Wooden Bed"}
                    </div>
                  }
                />
              </div>
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__qkYfz)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__juzNa
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___48Q3X)}
            >
              <div className={classNames(projectcss.all, sty.column__fW43R)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fv0Dk
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__guLfs
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__uB24I
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cstXa
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__rD9Fw)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yxh41
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__jVEbM)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f2YZYckXJeE,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___9So3I
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__a2D5R)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___9XKhc
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__vDxiX)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f3MiMyYimZ0,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__u1Jvc
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__hkTvB)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gYohz
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__c7Bpf)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f4AF6LDx447Yl,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zunCm
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__vmkkK)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__obMbQ
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__x5Nr7)}
            >
              <div className={classNames(projectcss.all, sty.column__dbZml)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__zcxV)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gq0FJ)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b1GShyHTjVshz,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__z0OoO)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__pQrn)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__cUam)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b2PHhMNfXbuCz,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__dRMs)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___7KdAe)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__yorhE)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b36GzoZlVFr8XJ,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__fpnLj)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__aaXl)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: adidas8A8TrpRztth,
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__czS8R)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: hmF0QHspbUgvy,
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__nQi2C)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: kappaYvzubA4M7Mg,
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__tNk95)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: lacosteB6EjqEha8XcA,
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__s58Y)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: levisTToXfiy87MX,
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps,
    })

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicHome"
  } else {
    func.displayName = `PlasmicHome.${nodeName}`
  }
  return func
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
  }
)

export default PlasmicHome
/* prettier-ignore-end */
